### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Landroidx/core/os/BuildCompat;

### ISSUE THREAD

**Issue by bhautikkeraliya** [InflationX/Calligraphy#37]
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.os.BuildCompat" on path: DexPathList.
Suppressed: java.io.IOException: No original dex files found for dex location

About My App:-
-App in java language
-not using android x
-App testing in Android 8.0 (oreo) - SDK (26)

**Comment by sathamkhussain** [comment]
@bhautikkeraliya Did you fix this issue? Am also facing the same issue.

**Comment by SwathyMothilal** [comment]
Stack trace: Caused by:  Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.os.BuildCompat" on path:DexpathList

@bhautikkeraliya  Even I am facing the same issue

**Comment by chrisfoulds** [comment]
Same issue

**Comment by zhangweifu0621** [comment]
Same Issue

**Comment by sesesmith30** [comment]
i used version `'io.github.inflationx:viewpump:1.0.0'` of viewPump and it worked

**Comment by candeiasdan** [comment]
Same issue. Not working with `io.github.inflationx:viewpump:2.0.3`

**Comment by yatochk** [comment]
If I used 'io.github.inflationx:viewpump:1.0.0' then I get crash on android 10

**Comment by aalmodovarr** [comment]
Any news about this issue?

**Comment by scmyers11** [comment]
This is causing crashes for our users in production. Is there any movement on this?

**Comment by AhmedBadrSayed** [comment]
I think the only solution right now that works on all android versions is to migrate to android x

**Comment by mohkin** [comment]
Same issue

**Comment by aalmodovarr** [comment]
It works by migrating to **AndroidX** and with:

> implementation 'io.github.inflationx: calligraphy3: 3.1.1'
> implementation 'io.github.inflationx: viewpump: 2.0.3'

**Comment by chrisjenx** [comment]
Migrate to Androidx the tools team made it easier especially with the intro of migration in the build tools. https://developer.android.com/jetpack/androidx/migrate#migrate_an_existing_project_using_android_studio

**Comment by wiz-hjhan** [comment]
migrate to android X. 
still remain issue.

03-24 02:32:33.281 W 21246    21246    System.err:                             Caused by: android.content.res.Resources$NotFoundException: Unable to find resource ID #0x20a014e 
03-24 02:32:33.282 W 21246    21246    System.err:                             	at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:279) 
03-24 02:32:33.282 W 21246    21246    System.err:                             	at android.content.res.Resources.getResourceEntryName(Resources.java:2002) 
03-24 02:32:33.282 W 21246    21246    System.err:                             	at io.github.inflationx.calligraphy3.Calligraphy.matchesResourceIdName(Calligraphy.java:94) 
03-24 02:32:33.282 W 21246    21246    System.err:                             	at io.github.inflationx.calligraphy3.Calligraphy.isActionBarTitle(Calligraphy.java:57) 
03-24 02:32:33.282 W 21246    21246    System.err:                             	at io.github.inflationx.calligraphy3.Calligraphy.getStyleForTextView(Calligraphy.java:33) 
03-24 02:32:33.282 W 21246    21246    System.err:                             	at io.github.inflationx.calligraphy3.Calligraphy.onViewCreatedInternal(Calligraphy.java:139) 
03-24 02:32:33.282 W 21246    21246    System.err:                             	at io.github.inflationx.calligraphy3.Calligraphy.onViewCreated(Calligraphy.java:117) 
03-24 02:32:33.282 W 21246    21246    System.err:                             	at io.github.inflationx.calligraphy3.CalligraphyInterceptor.intercept(CalligraphyInterceptor.java:19) 
03-24 02:32:33.282 W 21246    21246    System.err:                             	at io.github.inflationx.viewpump.internal.-InterceptorChain.proceed(-InterceptorChain.kt:30) 
03-24 02:32:33.283 W 21246    21246    System.err:                             	at io.github.inflationx.viewpump.ViewPump.inflate(ViewPump.kt:36) 
03-24 02:32:33.283 W 21246    21246    System.err:                             	at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater$WrapperFactory2.onCreateView(-ViewPumpLayoutInflater.kt:358) 
03-24 02:32:33.283 W 21246    21246    System.err:                             	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:772) 
03-24 02:32:33.283 W 21246    21246    System.err:                             	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
03-24 02:32:33.283 W 21246    21246    System.err:                             	at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
03-24 02:32:33.283 W 21246    21246    System.err:                             	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
03-24 02:32:33.283 W 21246    21246    System.err:                             	at android.view.LayoutInflater.rInflate(LayoutInflater.java:866) 
03-24 02:32:33.284 W 21246    21246    System.err:                             	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
03-24 02:32:33.284 W 21246    21246    System.err:                             	at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
03-24 02:32:33.284 W 21246    21246    System.err:                             	at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:57) 
03-24 02:32:33.284 W 21246    21246    System.err:                             	at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
03-24 02:32:33.284 W 21246    21246    System.err:                             	at io.github.inflationx.viewpump.internal.-ViewPumpLayoutInflater.inflate(-ViewPumpLayoutInflater.kt:48) 
03-24 02:32:33.284 W 21246    21246    System.err:                             	at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
03-24 02:32:33.284 W 21246    21246    System.err:                             	at bNB.getView(PG:20) 
03-24 02:32:33.285 W 21246    21246    System.err:                             	at android.widget.AbsListView.obtainView(AbsListView.java:2366) 
03-24 02:32:33.285 W 21246    21246    System.err:                             	at android.widget.ListView.onMeasure(ListView.java:1285) 
03-24 02:32:33.285 W 21246    21246    System.err:                             	at android.view.View.measure(View.java:23169) 
03-24 02:32:33.285 W 21246    21246    System.err:                             	at bPh.d(PG:56) 
03-24 02:32:33.285 W 21246    21246    System.err:                             	at bNE.a(PG:8) 
03-24 02:32:33.285 W 21246    21246    System.err:                             	at bBp.<init>(PG:11) 
03-24 02:32:33.285 W 21246    21246    System.err:                             	at org.chromium.content.browser.input.SelectPopup.show(PG:38) 
03-24 02:32:33.286 W 21246    21246    System.err:                             	at android.os.MessageQueue.nativePollOnce(Native Method) 
03-24 02:32:33.286 W 21246    21246    System.err:                             	at android.os.MessageQueue.next(MessageQueue.java:326) 
03-24 02:32:33.287 W 21246    21246    System.err:                             	at android.os.Looper.loop(Looper.java:160) 
03-24 02:32:33.287 W 21246    21246    System.err:                             	at android.app.ActivityThread.main(ActivityThread.java:6669) 
03-24 02:32:33.287 W 21246    21246    System.err:                             	at java.lang.reflect.Method.invoke(Native Method) 
03-24 02:32:33.287 W 21246    21246    System.err:                             	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
03-24 02:32:33.288 W 21246    21246    System.err:                             	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by chrisfoulds** [comment]
Look at the code base, this is no longer actively maintained.
It took about 4hrs to rip this out and manually specify the fonts in my labels and make all the problems go away, I would advise others to do the same.

**Comment by lsk-boy-f** [comment]
Same issue. Not working with io.github.inflationx:viewpump:2.0.3

**Comment by chrisjenx** [comment]
We mentioned in the changelog we only support androidx now, if you still have legacy items use jetifier:

gradle.properties:
```
android.useAndroidX=true
android.enableJetifier=true
```
